name: Auto Update Configs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours max

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # cache pip dependencies

    - name: Cache Xray Core
      id: cache-xray
      uses: actions/cache@v3
      with:
        path: |
          xray
          geoip.dat
          geosite.dat
        key: xray-core-linux-64-v1

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Aggregator
      run: |
        python aggregator.py

    - name: Run Tester
      run: |
        python tester.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        git add all_configs.txt tcp_passed.txt real_delay_passed.txt
        
        # Check if there are changes
        if git diff --staged --quiet; then
          echo "⚠️ No changes to commit."
        else
          git commit -m "🔄 Update configs [$(date)]"
          git push
        fi
