name: Auto Update Configs

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Aggregator
      run: |
        python aggregator.py

    - name: Run Tester
      run: |
        python tester.py
      env:
        TCP_CONCURRENCY: 500
        REAL_DELAY_CONCURRENCY: 50
        TCP_TIMEOUT: 3.0
        REAL_DELAY_TIMEOUT: 5.0

    - name: Debug File List
      run: ls -lh

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        git add .
        
        if output=$(git status --porcelain) && [ -z "$output" ]; then
          echo "⚠️ No changes detected to commit."
        else
          git commit -m "🔄 Update server list [$(date)]"
          git push
        fi
