name: Auto Update Configs

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Collector
      run: |
        python collector.py

    - name: Debug File List (Check if file exists)
      run: ls -lh

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        
        # اضافه کردن تمام فایل‌های جدید و تغییر کرده
        git add .
        
        # بررسی وضعیت و کامیت کردن
        if output=$(git status --porcelain) && [ -z "$output" ]; then
          echo "⚠️ No changes detected to commit."
        else
          git commit -m "🔄 Update server list [$(date)]"
          git push
        fi
